import { createSlice } from '@reduxjs/toolkit';
import { caseReducer } from './reducer';

const initialState = {
  value: [],
  error: null,
  status: 'idle',
};

export const offersSlice = createSlice({
  name: 'offers',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: caseReducer,
});

const selectOffers = (state) => state.offers.value;
const selectOffersError = (state) => state.offers.error;
const selectOffersStatus = (state) => state.offers.status;
const offersReducer = offersSlice.reducer;

export { offersReducer, selectOffers, selectOffersError, selectOffersStatus };
